--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ACM-PocketMine-MP/DiscordWebhookAPI
build-by-default: true
branches:
- PM5
projects:
  DiscordWebhookAPI:
    path: ""
    model: virion
    type: library
    lint:
      phpstan: false
...
